{
 "title": "OpenAPI Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "server", "label": "server", "query": { "query": "label_values(ipserver)" } },
   {
    "name": "service",
    "label": "service",
    "query": {
     "query": "label_values(up{ipserver=~\"$server\"},application)"
    }
   },
   {
    "name": "api",
    "label": "api",
    "query": {
     "query": "label_values(http_request_duration_ms_bucket{application=~\"$service\"},route)"
    }
   },
   {
    "name": "queue",
    "label": "queue",
    "query": {
     "query": "label_values(queue_received_total{application=~\"$service\"},queue_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(route, application, method) (rate(http_request_duration_ms_sum{application=~\"$service\", route=~\"$api\"}[5m])) / sum by(route, application, method) (rate(http_request_duration_ms_count{application=~\"$service\", route=~\"$api\"}[5m]))",
     "legendFormat": "{{application}}:{{method}}: {{route}}"
    }
   ]
  },
  {
   "title": "Latency ALL",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_ms_sum{application=~\"$service\", route=~\"$api\"}[5m])) / sum(rate(http_request_duration_ms_count{application=~\"$service\", route=~\"$api\"}[5m]))",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(application, route, method) (rate(http_request_duration_ms_count{application=~\"$service\", route=~\"$api\"}[1m]))",
     "legendFormat": "{{application}}:{{method}}:{{route}}"
    }
   ]
  },
  {
   "title": "Throughput All",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_ms_count{application=~\"$service\", route=~\"$api\"}[1m]))",
     "legendFormat": "Throughput"
    }
   ]
  },
  {
   "title": "P99",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(route, application, method, le) (rate(http_request_duration_ms_bucket{application=~\"$service\", route=~\"$api\"}[1m])))",
     "legendFormat": "{{application}}:{{method}}:{{route}}"
    }
   ]
  },
  {
   "title": "P95",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(route, application, method, le) (rate(http_request_duration_ms_bucket{application=~\"$service\", route=~\"$api\"}[1m])))",
     "legendFormat": "{{application}}:{{method}}:{{route}}"
    }
   ]
  },
  {
   "title": "P50",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(route, application, method, le) (rate(http_request_duration_ms_bucket{application=~\"$service\", route=~\"$api\"}[1m])))",
     "legendFormat": "{{application}}:{{method}}:{{route}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_system_seconds_total{application=~\"$service\"}[1m])",
     "legendFormat": "process_cpu_system_seconds_total-{{application}}"
    },
    {
     "expr": "rate(process_cpu_user_seconds_total{application=~\"$service\"}[1m])",
     "legendFormat": "process_cpu_user_seconds_total-{{application}}"
    },
    {
     "expr": "rate(process_cpu_seconds_total{application=~\"$service\"}[1m])",
     "legendFormat": "process_cpu_seconds_total-{{application}}"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(route, method, application) (rate(http_request_duration_ms_count{status_code!~\"2..|304\", application=~\"$service\"}[5m])) / sum by(route, method, application) (rate(http_request_duration_ms_count{application=~\"$service\"}[5m]))",
     "legendFormat": "{{application}}:{{method}}:{{route}}"
    }
   ]
  },
  {
   "title": "Error rate all",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_ms_count{status_code!~\"2..|304\", application=~\"$service\"}[5m])) / sum(rate(http_request_duration_ms_count{application=~\"$service\"}[5m]))",
     "legendFormat": "Error rate"
    }
   ]
  },
  {
   "title": "Heap memory use",
   "type": "timeseries",
   "description": "Trong khoảng 700–1400MB",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_size_used_bytes{application=~\"$service\"}",
     "legendFormat": "{{application}}-{{__name__}}"
    },
    {
     "expr": "nodejs_heap_size_total_bytes{application=~\"$service\"}",
     "legendFormat": "{{application}}-{{__name__}}"
    }
   ]
  },
  {
   "title": "Ram use",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{application=~\"$service\"}",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "Event Loop",
   "type": "timeseries",
   "description": "P50\t> 10 ms\nP90\t> 30 ms\nP95\t> 40 ms\nP99\t> 80 ms",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_p99_seconds{application=~\"$service\"}",
     "legendFormat": "{{application}}-{{__name__}}"
    },
    {
     "expr": "nodejs_eventloop_lag_p90_seconds{application=~\"$service\"}",
     "legendFormat": "{{application}}-{{__name__}}"
    },
    {
     "expr": "nodejs_eventloop_lag_p50_seconds{application=~\"$service\"}",
     "legendFormat": "{{application}}-{{__name__}}"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{application=~\"$service\"}",
     "legendFormat": "nodejs_eventloop_lag_seconds-{{application}}"
    }
   ]
  },
  {
   "title": "Queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum by(instance, queue_name) (rate(queue_handler_duration_ms_sum{application=~\"$service\", queue_name=~\"$queue\"}[5m])) / sum by(instance, queue_name) (rate(queue_handler_duration_ms_count{application=~\"$service\", queue_name=~\"$queue\"}[5m]))",
       "legendFormat": "{{instance}}:{{queue_name}}"
      }
     ]
    },
    {
     "title": "Latency ALL",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(queue_handler_duration_ms_sum{application=~\"$service\", queue_name=~\"$queue\"}[5m])) / sum(rate(queue_handler_duration_ms_count{application=~\"$service\", queue_name=~\"$queue\"}[5m]))",
       "legendFormat": "Latency"
      }
     ]
    },
    {
     "title": "Throughput",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "mps" } },
     "targets": [
      {
       "expr": "sum by(instance, queue_name) (rate(queue_handler_duration_ms_count{application=~\"$service\", queue_name=~\"$queue\"}[1m]))",
       "legendFormat": "{{instance}}:{{queue_name}}"
      }
     ]
    },
    {
     "title": "Throughput All",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "mps" } },
     "targets": [
      {
       "expr": "sum(rate(queue_handler_duration_ms_count{application=~\"$service\", queue_name=~\"$queue\"}[1m]))",
       "legendFormat": "Throughput"
      }
     ]
    },
    {
     "title": "P99",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(queue_name, instance, le) (rate(queue_handler_duration_ms_bucket{application=~\"$service\", queue_name=~\"$queue\"}[1m])))",
       "legendFormat": "{{instance}}:{{queue_name}}"
      }
     ]
    },
    {
     "title": "P95",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(queue_name, instance, le) (rate(queue_handler_duration_ms_bucket{application=~\"$service\", queue_name=~\"$queue\"}[1m])))",
       "legendFormat": "{{instance}}:{{queue_name}}"
      }
     ]
    },
    {
     "title": "P90",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum by(queue_name, instance, le) (rate(queue_handler_duration_ms_bucket{application=~\"$service\", queue_name=~\"$queue\"}[1m])))",
       "legendFormat": "{{instance}}:{{queue_name}}"
      }
     ]
    },
    {
     "title": "P50",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(queue_name, instance, le) (rate(queue_handler_duration_ms_bucket{application=~\"$service\", queue_name=~\"$queue\"}[1m])))",
       "legendFormat": "{{instance}}:{{queue_name}}"
      }
     ]
    }
   ]
  }
 ]
}