spring.application.name=demo
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

spring.data.redis.host=192.168.18.203
spring.data.redis.port=6379
spring.data.redis.password=
spring.data.redis.timeout=2000

spring.data.redis.lettuce.pool.max-active=20
spring.data.redis.lettuce.pool.max-idle=10
spring.data.redis.lettuce.pool.min-idle=2

spring.datasource.url=jdbc:postgresql://192.168.18.213:5432/FXOnline
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# Bật SQL statement
# mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

# Hoặc bật debug cho MyBatis qua Spring Boot logging
# logging.level.com.example.demo.infrastructure.mybatis.TranslogMapper=DEBUG
# logging.level.org.mybatis=DEBUG
# logging.level.org.mybatis.spring=DEBUG

spring.kafka.bootstrap-servers=192.168.18.192:9092
spring.kafka.consumer.group-id=md-group-1

spring.kafka.listener.type=batch
spring.kafka.listener.concurrency=8
spring.kafka.listener.ack-mode=manual

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
spring.kafka.consumer.max-poll-records=5000

market.kafka.listener.id=marketListener-12321
market.kafka.listener.topics=market-quote

mybatis.mapper-locations=classpath*:/mapper/*.xml