server.port=8080
spring.application.name=demo
spring.main.allow-bean-definition-overriding=true
# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.data.redis.host=192.168.18.203
spring.data.redis.port=6379
spring.data.redis.password=
spring.data.redis.timeout=2000

spring.data.redis.lettuce.pool.max-active=20
spring.data.redis.lettuce.pool.max-idle=10
spring.data.redis.lettuce.pool.min-idle=2

spring.datasource.url=jdbc:postgresql://192.168.18.213:5432/FXOnline
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

mybatis.configuration.default-executor-type=BATCH
mybatis.configuration.jdbc-type-for-null=NULL
mybatis.executor-type=batch
# Bật SQL statement
# mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

# Hoặc bật debug cho MyBatis qua Spring Boot logging
# logging.level.com.example.demo.infrastructure.mybatis.TranslogMapper=DEBUG
logging.level.org.mybatis=DEBUG
logging.level.org.mybatis.spring=DEBUG

mybatis.mapper-locations=classpath*:mapper/*.xml

spring.kafka.bootstrap-servers=192.168.18.192:9092
spring.kafka.consumer.group-id=md-group-1

spring.kafka.listener.type=batch
spring.kafka.listener.concurrency=8
spring.kafka.listener.ack-mode=manual

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
spring.kafka.consumer.max-poll-records=100000
spring.kafka.consumer.properties.fetch.max.wait.ms=500
spring.kafka.consumer.properties.fetch.max.bytes=33554432
spring.kafka.consumer.properties.max.partition.fetch.bytes=33554432

market.kafka.listener.id=marketListener-12321
market.kafka.listener.topics=market-quote


# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha



otel.exporter.otlp.endpoint=http://192.168.26.14:4318
otel.traces.exporter=otlp
otel.metrics.exporter=otlp
otel.logs.exporter=otlp

otel.propagators=tracecontext,baggage
otel.resource.attributes.deployment.environment=fundtrack
otel.resource.attributes.service.name=fundtrack
otel.resource.attributes.service.namespace=fundtrack

# Expose actuator endpoints (enable metrics endpoint)
management.endpoints.web.base-path=/actuator
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.metrics.enable.all=true
management.server.port=8080
management.endpoint.prometheus.access=READ_ONLY

# Number of worker threads for translog queue
translog.worker.count=4
translog.flush.millis=1000

# Symbol worker settings
symbol.worker.count=4
symbol.flush.interval.ms=1000

# Disruptor settings
decode.ring.buffer.size=2048
market.ring.buffer.size=2048
market.disruptor.num.workers=4


gateway.base-url=http://192.168.15.64:8080/api/v1
gateway.cb-name=gatewayCB
gateway.retry-name=gatewayRetry
resilience4j.circuitbreaker.instances.gatewayCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.gatewayCB.slow-call-rate-threshold=70
resilience4j.circuitbreaker.instances.gatewayCB.slow-call-duration-threshold=4s
resilience4j.circuitbreaker.instances.gatewayCB.minimum-number-of-calls=10
resilience4j.circuitbreaker.instances.gatewayCB.sliding-window-size=20
resilience4j.circuitbreaker.instances.gatewayCB.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.gatewayCB.permitted-number-of-calls-in-half-open-state=3

resilience4j.retry.instances.gatewayRetry.max-attempts=3
resilience4j.retry.instances.gatewayRetry.wait-duration=500ms
resilience4j.retry.instances.gatewayRetry.enable-exponential-backoff=true
resilience4j.retry.instances.gatewayRetry.exponential-backoff-multiplier=2
resilience4j.retry.instances.gatewayRetry.retry-exceptions=\
org.springframework.web.reactive.function.client.WebClientRequestException,\
java.util.concurrent.TimeoutException,\
java.io.IOException
